### ISSUE TITLE
opts.slash doesnt keep correct case

### ISSUE THREAD

**Issue by tekadept** [udlei/redirect.center#11]
I am trying to do a redirect to a Discord invite url which is case sensitive.
I have discord.gg.opts-slash.EhJeY6y.redirect.center.

yet the redirect does https://discord.gg/ehjey6y which won't work as its case sensitive.

**Comment by udlei** [comment]
@tekadept you can't use uppercase in CNAME entries but you can encode your upper character.

Try this:
discord.gg.opts-slash.%45h%4Ae%596y.redirect.center

I created a example for you in http://test.nati.biz.

Check http://www.w3schools.com/tags/ref_urlencode.asp for other uppercase character.

Let me know if you have any problem.
