### ISSUE TITLE
Redirect to GitHub profile

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [udlei/redirect.center#13]
@udlei 

----

Hello, 😄 

I would like to redirect my domain **`http://github.suriyaa.tk/`** to **`https://github.com/SuriyaaKudoIsc`**.

How can I do this?

*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

(PS: I use [CloudFlare](https://www.cloudflare.com/).)

**Comment by udlei** [comment]
Hi @SuriyaaKudoIsc,

First of all, you need to desactive CloudFlare on your entry github.suriyaa.tk, after that just alter your CNAME to: github.com.opts-slash.SuriyaaKudoIsc.redirect.center.

I've created a working example to you: http://gwfztvgu.nati.biz

Any problem, let me know.

**Comment by SuriyaaKudoIsc** [comment]
@udlei Thank you for your fast response! 👍

It works for me on CloudFlare:

![cloudflare-settings](https://cloud.githubusercontent.com/assets/5073946/22182416/39e63b4a-e0a5-11e6-9162-9278db8f0488.png)

I must only disable the CloudFlare Proxy. 😄


*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

(PS: Can you remove the example: http://gwfztvgu.nati.biz? I don't like any external redirects to my GitHub profile. 😏)

**Comment by udlei** [comment]
Example removed. 👍

**Comment by SuriyaaKudoIsc** [comment]
@udlei Thank you! 😄
