### ISSUE TITLE
Any way to use a file name? 

### ISSUE THREAD

**Issue by BitpopCoin** [udlei/redirect.center#14]

**Comment by davchana** [comment]
Please give an example of `from`  & `to` URL.

**Comment by BitpopCoin** [comment]
Link.google.com to google.com/link.html

**Comment by davchana** [comment]
How will this service guess that `link` in `link.redirect.center` means link.**html**? How will it reach/guess/deduce word html?

This service can not add data on its own. How will it know that the file/word is html/php/js/txt/png/etc/etc?

**Comment by udlei** [comment]
Hi @davchana, there is not way to use a file name to redirect your url, you must use a dns entry to redirect. For example, if you want to redirect link.yourdomain.com to http://anydomain/link, you must use:

link.youdomain.com CNAME TO anydomain.opts-slash.link.redirect.center

redirect.center won't guess your extension, you must create a directory link/ and put your index.html inside.

any problem, let me know.

**Comment by BitpopCoin** [comment]
Smart thanks
