### ISSUE TITLE
Redirect with a path

### ISSUE THREAD

**Issue by rogeriochaves** [udlei/redirect.center#4]
What about something like:

`www.oldwebsite.com. CNAME www.newwebsite.com.slash.somewhere.redirect.center`?

So it would become `www.newwebsite.com/somewhere`

Oh, and great idea btw!

**Comment by udlei** [comment]
Sorry for the delay.

It's really a good idea. I'm rewriting the ways to redirect to allow new features. Another 2 weeks do commit.

thanks

**Comment by jamesholcomb** [comment]
Did this get implemented?  If so, can you provide a configuration example?

**Comment by udleinati** [comment]
@jamesholcomb the last example on http://redirect.center explain that situation.

www.my-domain.com.opts-slash.jobs.redirect.center
