### ISSUE TITLE
Redirect with path (opts-uri) not working?

### ISSUE THREAD

**Issue by ssterjo** [udlei/redirect.center#6]
From what I understand, the opts-uri option is to redirect to the target domain by preserving the path (www.alias.com/page --> www.real.com/page), right?
If yes, then is it only me or is it not working? I tried it multiple times, but I don't seem to get it to work.

(PS: just an additional config question for the root domain redirect. If I add an A record to the redirect.center IP, should I also add a CNAME record like redirect.alias.com --> real.com.redirect.center, or alias.com --> real.com.redirect.center. So what I'm asking is, do I need to add the redirect. part in the beginning or create any cname with cname.alias.com? thanks)

**Comment by udlei** [comment]
Hi,

Yes, it's right and work fine. Can you tell me what is your domain to i can check?

For addicional configuration, do you need use:
alias.com A to 54.84.55.102
redirect.alias.com CNAME to real.com.opts-uri.redirect.center

If you have any questions, let me know.

**Comment by AR-Student824** [comment]
ggggg
