### ISSUE TITLE
TXT record instead of CNAME

### ISSUE THREAD

**Issue by kolobus** [udlei/redirect.center#9]
Hi.

I'm curious. Why not to use separate DNS TXT record for storing redirecting URL? It will be even simplier than parsing all from CNAME.

**Comment by udlei** [comment]
Hi @kolobus, 
The main reason is my client interfaces, some do not have the TXT option available for use...

**Comment by kolobus** [comment]
@udlei

wow. Never seen a single one dns editor without txt records in this decade - txt are essential for SPF, DKIM, domain validations and tons of other things. It's better not to use such registrars / service providers :)

Anyway consider making txt record for url and hacky cname as a fallback mechanism.

I made it like this:

```
$dnstxt = @dns_get_record("_url.".$domain, DNS_TXT);
if ($dnstxt) {
        $redirect = $dnstxt[0]["txt"];
}
```
And in Zones I can put any CNAME/A pointing to host and special subdomain:

```
_url 3600  IN TXT "https://example.com/some/url"
```

**Comment by udlei** [comment]
@kolobus is a harsh reality here ...

There is another redirect, http://redirect.name based in TXT. I will also consider putting in an upcoming release.
